version: "3.8"

services:
  tg-antispam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-antispam
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - ./logs:/app/logs
      # 如果使用证书文件，取消注释以下行
      # - ./certs:/app/certs
