version: "3"

services:
  app:
    build: .
    restart: always
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-tgantispam}
      MYSQL_DATABASE: tgantispam
      MYSQL_USER: ${MYSQL_USER:-tgantispam}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-tgantispam}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
