version: "3.8"

services:
  tg-antispam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-antispam
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
      # Webhook配置
      - WEBHOOK_POINT=${WEBHOOK_POINT}
      - LISTEN_PORT=${LISTEN_PORT:-8443}
      - CERT_FILE=${CERT_FILE:-}
      - KEY_FILE=${KEY_FILE:-}
      - LOG_DIR=/app/logs
    ports:
      - "${LISTEN_PORT:-8443}:${LISTEN_PORT:-8443}"
    volumes:
      - ./logs:/app/logs
      # 如果使用证书文件，取消注释以下行
      # - ./certs:/app/certs
