# TG-Antispam Configuration

# Bot Configuration
bot:
  # Telegram Bot Token (required)
  # get token from @BotFather: https://t.me/BotFather
  token: ""

  # group_id: 处理指定群组（-1 表示所有群组）
  group_id: -1

  # 最大并发处理消息数量（避免资源耗尽）
  max_concurrent_messages: 100

  # Webhook Configuration
  webhook:
    # Public webhook URL (required) - e.g., https://yourdomain.com/webhook
    endpoint: ""

    # listen port, may be different the port int endpoint
    listen_port: "8443"

    # debug path, for debug webhook
    debug_path: "/debug"

    # SSL Certificate file path (optional if using HTTPS proxy like Nginx)
    cert_file: ""

    # SSL Key file path (optional if using HTTPS proxy like Nginx)
    key_file: ""

# Database Configuration
database:
  # Whether to enable database support
  enabled: false

  host: "localhost"

  port: 3306

  username: "root"

  password: ""

  dbname: "tgantispam"

  charset: "utf8mb4"

# Logging Configuration
logger:
  # Directory for log files
  directory: "logs"

  # Timezone for logs (IANA timezone database names)
  # Examples: "Asia/Shanghai", "America/New_York", "Europe/London", "UTC", "Local"
  timezone: "Local"

  # Minimum log level to output
  # Available levels: "DEBUG", "INFO", "WARNING", "ERROR", "FATAL"
  level: "INFO"

  # Log format pattern with placeholders
  # Available placeholders: %{level}, %{time}, %{file}, %{line}, %{message}
  # Example: "[%{level}] %{time} %{file}:%{line}: %{message}"
  format: "[%{level}] %{time} %{file}:%{line}: %{message}"

  # Time format for timestamp in logs
  # Uses Go's time formatting: https://golang.org/pkg/time/#Time.Format
  # Example: "2006/01/02 15:04:05" (Year/Month/Day Hour:Minute:Second)
  time_format: "2006/01/02 15:04:05"

  # Log file rotation settings
  rotation:
    # Maximum size of log files in megabytes before rotating
    max_size: 10

    # Maximum number of old log files to retain
    max_backups: 30

    # Maximum number of days to retain old log files
    max_age: 90

    # Whether to compress rotated logs
    compress: true

# Anti-Spam Settings
antispam:
  # restrict premium user by default
  ban_premium: true

  # restrict random username by default
  ban_random_username: true

  # restrict emojis in name by default
  ban_emoji_name: true

  # restrict suspicious links in bio by default
  ban_bio_link: true

  # use CAS (Combot Anti-Spam) by default
  use_cas: true

# Gemini API Configuration
ai_api:
  # Gemini API Key
  gemini_api_key: ""

  # Gemini model
  gemini_model: "gemini-2.0-flash"
