# TG-Antispam Configuration

# Bot Configuration
bot:
  # Telegram Bot Token (required)
  # 从 @BotFather 获取: https://t.me/BotFather
  token: ""

  # Webhook Configuration
  webhook:
    # Public webhook URL (required) - e.g., https://yourdomain.com/webhook
    # 公开访问的Webhook URL，必须是HTTPS链接
    endpoint: ""

    # listen port, may be different the port int endpoint
    # 程序监听端口，可以和endpoint中的端口不一样
    listen_port: "8443"

    # debug path, for debug webhook
    # 调试路径，用于调试Webhook
    debug_path: "/debug"

    # SSL Certificate file path (optional if using HTTPS proxy like Nginx)
    # SSL证书文件路径 (如果使用Nginx等反向代理，可不设置)
    cert_file: ""

    # SSL Key file path (optional if using HTTPS proxy like Nginx)
    # SSL密钥文件路径 (如果使用Nginx等反向代理，可不设置)
    key_file: ""

# Database Configuration
database:
  # Whether to enable database support
  # 是否启用数据库支持
  enabled: false

  # Database host
  # 数据库主机地址
  host: "localhost"

  # Database port
  # 数据库端口
  port: 3306

  # Database username
  # 数据库用户名
  username: "root"

  # Database password
  # 数据库密码
  password: ""

  # Database name
  # 数据库名称
  dbname: "tgantispam"

  # Database charset
  # 数据库字符集
  charset: "utf8mb4"

# Logging Configuration
logger:
  # Directory for log files
  # 日志文件保存目录
  directory: "logs"

  # Log file rotation settings
  # 日志文件轮转设置
  rotation:
    # Maximum size of log files in megabytes before rotating
    # 单个日志文件的最大大小(MB)，超过后将轮转
    max_size: 10

    # Maximum number of old log files to retain
    # 最多保留的旧日志文件数量
    max_backups: 30

    # Maximum number of days to retain old log files
    # 旧日志文件最多保留的天数
    max_age: 90

    # Whether to compress rotated logs
    # 是否压缩轮转的日志文件
    compress: true

# Anti-Spam Settings
antispam:
  # Whether restrict premium user by default
  # 是否默认限制Premium用户
  ban_premium: true

  # Whether to check for random usernames
  # 是否默认限制随机用户名用户
  ban_random_username: true

  # Whether to check for emojis in username
  # 是否默认限制用户名中的表情符号用户
  ban_emoji_name: true

  # Whether to check for suspicious links in bio
  # 是否默认限制用户个人简介中包含可以链接用户
  ban_bio_link: true

  # Whether to use CAS (Combot Anti-Spam)
  # 是否使用CAS(Combot反垃圾系统)检查
  use_cas: true
